Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      ArtifactRelation:
        centos_7:
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
      SupplierTemplateConfigs:
        - Name: 模板1
          Url: ros_templates/template.yaml
          PredefinedParameters: []
          AllowedRegions:
            - cn-beijing
            - cn-hangzhou
            - cn-heyuan
    TemplateConfigs:
      - Name: 模板1
        Url: ros_templates/template.yaml
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-heyuan
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      模板1:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo.png
      Locale: zh-CN
      Name: Memos社区版
      ShortDescription: Memos 是一款注重隐私的轻量级笔记解决方案，可让您轻松捕捉和分享您的想法。
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: EcsImage
    ArtifactName: memos
    Description: memos
    ArtifactProperty:
      ImageId: m-t4n3dwpg0jwfy4lr4vp8
      RegionId: ap-southeast-1
    SupportRegionIds:
      - cn-beijing
      - cn-heyuan
      - cn-hangzhou
