Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: 单机版
          PredefinedParameters:
            - Name: 热卖套餐，特价99元/年（限购1台）
              Parameters:
                EcsInstanceType:
                  - ecs.e-c1m1.large
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 40
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 3
                PayPeriodUnit: Month
                PayPeriod: 12
                PayType: PrePaid
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Normal
              Description: 固定带宽不限流量，新老同享，上云首选！
            - Name: 尝鲜套餐，只需0.3元/小时
              Parameters:
                EcsInstanceType:
                  - ecs.e-c1m1.large
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 40
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 3
                PayType: PostPaid
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Normal
              Description: 可用300元学生专属代金券抵扣！
            - Name: 自定义套餐
              Parameters: {}
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Custom
          AllowedRegions:
            - cn-beijing
            - cn-hangzhou
            - cn-heyuan
    TemplateConfigs:
      - Name: 单机版
        Url: ros_templates/template.yaml
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-heyuan
        PredefinedParameters:
          - Name: 热卖套餐，特价99元/年（限购1台）
            Parameters:
              EcsInstanceType:
                - ecs.e-c1m1.large
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 40
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 3
              PayPeriodUnit: Month
              PayPeriod: 12
              PayType: PrePaid
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Normal
            Description: 固定带宽不限流量，新老同享，上云首选！
          - Name: 尝鲜套餐，只需0.3元/小时
            Parameters:
              EcsInstanceType:
                - ecs.e-c1m1.large
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 40
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 3
              PayType: PostPaid
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Normal
            Description: 可用300元学生专属代金券抵扣！
          - Name: 自定义套餐
            Parameters: {}
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Custom
        ArchitectureDiagramUrl: 'https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/architecture/架构图.jpg'
        DeployScene: ECS
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: memos-
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      单机版:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo.jpg
      Locale: zh-CN
      Name: Memos社区版
      ShortDescription: Memos 是一款注重隐私的轻量级笔记解决方案，可让您轻松捕捉和分享您的想法。
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
